# Generated by Django 5.2.7 on 2025-10-15 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictionsnapshot',
            name='name',
        ),
        migrations.AddField(
            model_name='predictionsnapshot',
            name='alevel_ucas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='predictionsnapshot',
            name='average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionsnapshot',
            name='btec_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='predictionsnapshot',
            name='gcse_average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='predictionsnapshot',
            name='classification',
            field=models.CharField(blank=True, default='_', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='predictionsnapshot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
