# Generated by Django 5.2.7 on 2025-10-16 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mltrainingsample',
            name='user',
        ),
        migrations.RemoveField(
            model_name='school',
            name='admins',
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='predictionsnapshot',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='predictionsnapshot',
            old_name='average',
            new_name='average_percent',
        ),
        migrations.RenameField(
            model_name='predictionsnapshot',
            old_name='gcse_average',
            new_name='label',
        ),
        migrations.AlterUniqueTogether(
            name='weeklystat',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('user', 'name', 'level')},
        ),
        migrations.RemoveField(
            model_name='predictionsnapshot',
            name='alevel_ucas',
        ),
        migrations.RemoveField(
            model_name='predictionsnapshot',
            name='btec_points',
        ),
        migrations.RemoveField(
            model_name='predictionsnapshot',
            name='classification',
        ),
        migrations.AlterField(
            model_name='module',
            name='credits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='predictionsnapshot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weeklystat',
            name='week_start',
            field=models.DateField(unique=True),
        ),
        migrations.DeleteModel(
            name='Classroom',
        ),
        migrations.DeleteModel(
            name='MLTrainingSample',
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.RemoveField(
            model_name='module',
            name='assessment_type',
        ),
        migrations.RemoveField(
            model_name='module',
            name='grade_letter',
        ),
        migrations.RemoveField(
            model_name='module',
            name='predicted_percent',
        ),
        migrations.RemoveField(
            model_name='module',
            name='ucas_points',
        ),
        migrations.RemoveField(
            model_name='module',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='module',
            name='year',
        ),
    ]
