# Generated by Django 5.2.7 on 2025-10-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_simulationhistory_whatifscenario'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_milestone_reached',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='milestone_effects_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
