# Generated by Django 5.2.7 on 2025-10-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userprofile_first_milestone_reached_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='milestone_50_unlocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='milestone_60_unlocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='milestone_70_unlocked',
            field=models.BooleanField(default=False),
        ),
    ]
