# Generated by Django 5.2.7 on 2025-10-20 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_bugreport_feedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_so_far', models.FloatField()),
                ('credits_done', models.FloatField()),
                ('difficulty_index', models.FloatField()),
                ('performance_variance', models.FloatField()),
                ('engagement_score', models.FloatField()),
                ('predicted_average', models.FloatField()),
                ('predicted_classification', models.CharField(max_length=50)),
                ('ai_insight', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
