# Generated by Django 5.2.7 on 2025-10-20 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_aiinsightsummary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('university', 'University'), ('college', 'College'), ('gcse', 'GCSE')], max_length=20)),
                ('inputs', models.JSONField(blank=True, default=dict)),
                ('predicted_grade', models.CharField(max_length=32)),
                ('predicted_score', models.FloatField(blank=True, null=True)),
                ('confidence', models.FloatField(default=0.75)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubjectResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=64)),
                ('predicted_score', models.FloatField()),
                ('predicted_grade', models.CharField(blank=True, default='', max_length=8)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.simulationresult')),
            ],
        ),
    ]
