# Generated by Django 5.2.7 on 2025-10-20 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_simulationresult_subjectresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectresult',
            name='simulation',
        ),
        migrations.DeleteModel(
            name='SimulationResult',
        ),
        migrations.DeleteModel(
            name='SubjectResult',
        ),
    ]
