# Generated by Django 5.2.7 on 2025-10-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_subjectresult_simulation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='premium_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='predictionsnapshot',
            name='label',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
