# Generated by Django 5.2.7 on 2025-10-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_userprofile_premium_since_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_retrained_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Model Status',
                'verbose_name_plural': 'AI Model Status',
            },
        ),
    ]
