# Generated by Django 5.2.7 on 2025-10-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_smartinsight_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodelstatus',
            name='free_accuracy',
            field=models.FloatField(default=0.0, help_text='R² score for free model'),
        ),
        migrations.AddField(
            model_name='aimodelstatus',
            name='premium_accuracy',
            field=models.FloatField(default=0.0, help_text='R² score for premium model'),
        ),
    ]
