# Generated by Django 5.2.7 on 2025-10-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_aimodelstatus_free_accuracy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionsnapshot',
            name='classification',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
