# Generated by Django 5.2.7 on 2025-11-08 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_whatsnewentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='is_sample',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plannedmodule',
            name='is_sample',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='upcomingdeadline',
            name='is_sample',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sample_data_version',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='whatifscenario',
            name='is_sample',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='aiinsightfeedback',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='aiinsightfeedback',
            name='rating',
            field=models.SmallIntegerField(choices=[(1, 'helpful'), (-1, 'not_helpful')]),
        ),
    ]
