# Generated by Django 5.2.7 on 2025-11-12 17:59

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_userprofile_has_seen_welcome'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='completion_percent',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='module',
            name='grade_percent',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.CheckConstraint(condition=models.Q(('credits__gte', 0)), name='module_credits_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.CheckConstraint(condition=models.Q(('grade_percent__isnull', True), models.Q(('grade_percent__gte', 0.0), ('grade_percent__lte', 100.0)), _connector='OR'), name='module_grade_0_100_or_null'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.CheckConstraint(condition=models.Q(('completion_percent__gte', 0.0), ('completion_percent__lte', 100.0)), name='module_completion_0_100'),
        ),
    ]
